### ISSUE TITLE
fyi UUID assigned

### ISSUE THREAD

**Issue by JeffreySarnoff** [andreasnoack/GenericLinearAlgebra.jl#32]
`Assigning UUID 68167eab-4858-5bc0-b60f-9fa0a04dd39f to GenericLinearAlgebra`

**Comment by andreasnoack** [comment]
I don't think this UUID is METADATA compatible. I've added a project file with a METADAT compatible UUID. See https://github.com/andreasnoack/GenericLinearAlgebra.jl/blob/master/Project.toml
